spring:
  application:
    name: orderservice-test
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  liquibase:
    enabled: false
  kafka:
    jaas:
      enabled: false

logging:
  level:
    com.userservice: DEBUG
    org.springframework.test.context: DEBUG
    org.testcontainers: DEBUG
user-service:
  base-url: http://localhost:8081/user
resilience4j:
  circuitbreaker:
    instances:
      getUserByEmail:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 1
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10